image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.4

sources:
  - service

provider: aws

domainFilters:
 - CLUSTER_DNS_ZONE

registry: "txt"
txtPrefix: "txt."
txtOwnerId: "nginx-external-dns"

## options: sync, upsert-only
policy: sync
logLevel: info

rbac:
 serviceAccountName: external-dns
