image:
  name: registry.opensource.zalan.do/teapot/external-dns
  tag: v0.5.4

sources:
  - ingress

provider: aws

domainFilters:
 - CLUSTER_DNS_ZONE

annotationFilter: "kubernetes.io/ingress.class=nginx-internal"

registry: "txt"
txtPrefix: "txt."
txtOwnerId: "private-external-dns"

## options: sync, upsert-only
policy: sync
logLevel: info

rbac:
 serviceAccountName: external-dns
