---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: "kube-system"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: armando-ramirez.vila@capgemini.com
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the DNS-01 challenge provider
    dns01:
      providers:
      - name: route53
        route53:
          hostedZoneID: "Z31OVNF5EA1VAW"
          accessKeyID: "AKIAIEVWBEHS3EM2OFAA"
          secretAccessKeySecretRef:
            name: route53-config
            key: secret-access-key
          region: eu-west-1
