image:
  name: hashicorp/terraform:0.11.11
  entrypoint:  ["/bin/sh", "-c"]

stages:
  - build
  - deploy
  - undeploy

before_script:
  - curl -LO https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator && mv aws-iam-authenticator /usr/bin/aws-iam-authenticator && chmod +x /usr/bin/aws-iam-authenticator
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && mv kubectl /usr/bin/kubectl && chmod +x /usr/bin/kubectl
  - curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.12.3-linux-amd64.tar.gz | tar xvz && mv linux-amd64/helm /usr/bin/helm && chmod +x /usr/bin/helm
  - terraform init -force-copy=true

plan:
  stage: build
  tags:
   - blueharvest
   - terraform
  script:
   - terraform validate
   - terraform plan

apply:
  stage: deploy
  when: manual
  allow_failure: false
  dependencies:
   - plan
  tags:
   - blueharvest
   - terraform
  script:
   - terraform apply -input=false -auto-approve=true
   - terraform plan
  artifacts:
    name: "configuration"
    paths:
      - kubeconfig_*
      - config-map-aws-auth_*.yaml
      - ./*.ovpn
      - ./*_key
      - ./*_key.pub

destroy:
  stage: undeploy
  dependencies:
   - apply
  tags:
   - blueharvest
   - terraform
  when: manual
  allow_failure: false
  script:
   - terraform destroy -force