fullnameOverride: elasticsearch-logging
appVersion: "6.2.4"

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  tag: "6.2.4"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch-logging"
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    MINIMUM_MASTER_NODES: "2"
    NODE_NAME: "${NODE_NAME}"
    NETWORK_HOST: "${NODE_IP}"

client:
  name: coordinator
  replicas: 2
  serviceType: ClusterIP
  heapSize: "512m"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    # There is a bug, the name has to be data as well
    name: data
    size: "4Gi"
    # storageClass: "ssd"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

data:
  name: data
  exposeHttp: false
  replicas: 5
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "20Gi"
    # storageClass: "ssd"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1536Mi"
  podDisruptionBudget:
    enabled: false
    # minAvailable: 1
    maxUnavailable: 1